/* tslint:disable */
/* eslint-disable */
/**
 * Paystack
 * The OpenAPI specification of the Paystack API that merchants and developers can harness to build financial solutions in Africa.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: techsupport@paystack.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Configuration } from "./configuration";
import type { RequestArgs } from "./base";
import type { AxiosInstance, AxiosResponse } from 'axios';
import { RequiredError } from "./base";

export const DUMMY_BASE_URL = 'https://example.com'

/**
 * ============================================================================
 * STRIPE-QUALITY TYPED ERRORS
 * ============================================================================
 */

export class PaystackError extends Error {
    public status?: number;
    public code?: string;
    public rawError?: any;

    constructor(message: string, status?: number, code?: string, rawError?: any) {
        super(message);
        this.name = 'PaystackError';
        this.status = status;
        this.code = code;
        this.rawError = rawError;
        Object.setPrototypeOf(this, new.target.prototype);
    }
}

export class AuthenticationError extends PaystackError {
    constructor(message = 'Invalid secret key or unauthorized API request.', rawError?: any) {
        super(message, 401, 'unauthorized', rawError);
        this.name = 'AuthenticationError';
    }
}

export class RateLimitError extends PaystackError {
    constructor(message = 'Too many requests sent to Paystack API. Rate limit exceeded.', rawError?: any) {
        super(message, 429, 'rate_limit_exceeded', rawError);
        this.name = 'RateLimitError';
    }
}

export class InvalidRequestError extends PaystackError {
    constructor(message: string, status = 400, code = 'invalid_request', rawError?: any) {
        super(message, status, code, rawError);
        this.name = 'InvalidRequestError';
    }
}

export class IdempotencyError extends PaystackError {
    constructor(message = 'Idempotency conflict detected.', rawError?: any) {
        super(message, 409, 'idempotency_error', rawError);
        this.name = 'IdempotencyError';
    }
}

export class ApiConnectionError extends PaystackError {
    constructor(message = 'Network timeout or connection error contacting Paystack servers.', rawError?: any) {
        super(message, 500, 'api_connection_error', rawError);
        this.name = 'ApiConnectionError';
    }
}

export function parseAndThrowApiError(error: any): never {
    if (error.response) {
        const status = error.response.status;
        const data = error.response.data || {};
        const message = data.message || data.error || error.message || 'Paystack API Request Failed';

        if (status === 401) throw new AuthenticationError(message, data);
        if (status === 429) throw new RateLimitError(message, data);
        if (status === 409) throw new IdempotencyError(message, data);
        if (status >= 400 && status < 500) throw new InvalidRequestError(message, status, data.code || 'invalid_request', data);
        if (status >= 500) throw new ApiConnectionError(`Server error (${status}): ${message}`, data);
    }
    if (error.request) {
        throw new ApiConnectionError(`No response received from Paystack API: ${error.message}`, error);
    }
    throw new PaystackError(error.message || 'Unknown error occurred');
}

/**
 * ============================================================================
 * EXPONENTIAL BACKOFF RETRY & RESILIENCE ENGINE
 * ============================================================================
 */

function generateUUID(): string {
    if (typeof crypto !== 'undefined' && crypto.randomUUID) {
        return crypto.randomUUID();
    }
    return 'idemp_' + Math.random().toString(36).substring(2, 15) + Date.now().toString(36);
}

/**
 *
 * @throws {RequiredError}
 */
export const assertParamExists = function (functionName: string, paramName: string, paramValue: unknown) {
    if (paramValue === null || paramValue === undefined) {
        throw new RequiredError(paramName, `Required parameter ${paramName} was null or undefined when calling ${functionName}.`);
    }
}

export const setApiKeyToObject = async function (object: any, keyParamName: string, configuration?: Configuration) {
    if (configuration && configuration.apiKey) {
        const localVarApiKeyValue = typeof configuration.apiKey === 'function'
            ? await configuration.apiKey(keyParamName)
            : await configuration.apiKey;
        object[keyParamName] = localVarApiKeyValue;
    }
}

export const setBasicAuthToObject = function (object: any, configuration?: Configuration) {
    if (configuration && (configuration.username || configuration.password)) {
        object["auth"] = { username: configuration.username, password: configuration.password };
    }
}

export const setBearerAuthToObject = async function (object: any, configuration?: Configuration) {
    if (configuration && configuration.accessToken) {
        const accessToken = typeof configuration.accessToken === 'function'
            ? await configuration.accessToken()
            : await configuration.accessToken;
        object["Authorization"] = "Bearer " + accessToken;
    }
}

export const setOAuthToObject = async function (object: any, name: string, scopes: string[], configuration?: Configuration) {
    if (configuration && configuration.accessToken) {
        const localVarAccessTokenValue = typeof configuration.accessToken === 'function'
            ? await configuration.accessToken(name, scopes)
            : await configuration.accessToken;
        object["Authorization"] = "Bearer " + localVarAccessTokenValue;
    }
}


function setFlattenedQueryParams(urlSearchParams: URLSearchParams, parameter: any, key: string = ""): void {
    if (parameter == null) return;
    if (typeof parameter === "object") {
        if (Array.isArray(parameter) || parameter instanceof Set) {
            (parameter as any[]).forEach(item => setFlattenedQueryParams(urlSearchParams, item, key));
        }
        else {
            Object.keys(parameter).forEach(currentKey =>
                setFlattenedQueryParams(urlSearchParams, parameter[currentKey], `${key}${key !== '' ? '.' : ''}${currentKey}`)
            );
        }
    }
    else {
        if (urlSearchParams.has(key)) {
            urlSearchParams.append(key, parameter);
        }
        else {
            urlSearchParams.set(key, parameter);
        }
    }
}

export const setSearchParams = function (url: URL, ...objects: any[]) {
    const searchParams = new URLSearchParams(url.search);
    setFlattenedQueryParams(searchParams, objects);
    url.search = searchParams.toString();
}

// @ts-ignore
export const replaceWithSerializableTypeIfNeeded = function(key: string, value: any) {
    if (value instanceof Set) {
        return Array.from(value);
    } else {
        return value;
    }
}

export const serializeDataIfNeeded = function (value: any, requestOptions: any, configuration?: Configuration) {
    const nonString = typeof value !== 'string';
    const needsSerialization = nonString && configuration && configuration.isJsonMime
        ? configuration.isJsonMime(requestOptions.headers['Content-Type'])
        : nonString;
    return needsSerialization
        ? JSON.stringify(value !== undefined ? value : {}, replaceWithSerializableTypeIfNeeded)
        : (value || "");
}

export const toPathString = function (url: URL) {
    return url.pathname + url.search + url.hash
}

export const createRequestFunction = function (axiosArgs: RequestArgs, globalAxios: AxiosInstance, BASE_PATH: string, configuration?: Configuration) {
    return async <T = unknown, R = AxiosResponse<T>>(axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH): Promise<R> => {
        const targetAxios = configuration?.axiosInstance || axios;
        const axiosRequestArgs = {
            ...axiosArgs.options,
            url: (targetAxios.defaults.baseURL ? '' : configuration?.basePath ?? basePath) + axiosArgs.url
        };

        // Auto-inject Idempotency Key if header is missing
        if (!axiosRequestArgs.headers) {
            axiosRequestArgs.headers = {};
        }
        if (!axiosRequestArgs.headers['X-Idempotency-Key'] && !axiosRequestArgs.headers['x-idempotency-key']) {
            axiosRequestArgs.headers['X-Idempotency-Key'] = generateUUID();
        }

        const maxRetries = configuration?.maxRetries ?? 3;
        let attempt = 0;

        while (true) {
            try {
                return (await targetAxios.request(axiosRequestArgs)) as unknown as R;
            } catch (error: any) {
                const status = error.response?.status;
                const isRetryable = (!status || status === 429 || (status >= 500 && status < 600) || error.code === 'ECONNRESET' || error.code === 'ETIMEDOUT');

                if (attempt < maxRetries && isRetryable) {
                    attempt++;
                    const backoffMs = Math.min(300 * Math.pow(2, attempt) + Math.random() * 100, 4000);
                    await new Promise(resolve => setTimeout(resolve, backoffMs));
                    continue;
                }

                parseAndThrowApiError(error);
            }
        }
    };
}
